### ISSUE TITLE
Adding info or metadata to a stream?

### ISSUE THREAD

**Issue by madwill** [rtc-io/rtc-quickconnect#52]
Hi. 

I'm looking for a way to add some information about the video stream. Name, user role etc. We're prototyping a simple teacher/student/observer web app. 

With current highly automated way of doing so all streams are "anonymous" and i only get a generated ID but not much more. 

I've tried adding info to the stream before calling rtcConnection.addStream but i wasn't so lucky. 

I can't find the documentation. Do you have a way of identifying which stream is which so i can apply some of our internal logic in there ?

Thank you. 

ps: sorry to make this an issue. i could not find another way to communicate. Do you have a slack or irc channel ?

**Comment by madwill** [comment]
Having a user list manager on the side and matching user with quick connect generated ID i can almost reach my goal but i'm stuck at one particular case

Our teacher also use screen share to present learning objects. So they often send 2 streams, themselves and their screen share. I present the learning object in a "newscaster" type box at the top left of the teacher. 

Without either stream labeling or metadata i have no way of differing which is which.

**Comment by DamonOehlman** [comment]
@madwill no problems on making an issue.  We have a few options for communication but admittedly neither are super active:

- https://groups.google.com/forum/#!forum/rtc-io
- https://gitter.im/rtc-io/discuss

I personally quite like gitter but it seems to be struggling to get critical mass against slack, so maybe we should switch to that.

In terms of metadata sharing, what you are describing is a very common application-level problem and in all honesty, no clear way to solve it.  Firstly, I guess I'd suggest looking at using your own user identifying id alongside the quickconnect unique id - this is documented within the rtc-signaller docs here:

https://github.com/rtc-io/rtc-signaller#identifying-participants

This is more reliable than using the quickconnect generated id, because if does related to persistent id that relates to a user it will be more robust on handling browser refreshes, etc.

When it comes to communicating metadata about a stream, i.e. what is going to give you enough information to properly map a remote captured stream of a particular type, with it's destination container on the remote end, you are probably going to need some kind of P2P replicated data store to help you achieve this.  Typically I reach for [`rtc-mesh`](https://github.com/rtc-io/rtc-mesh) in combination with a few other tools to help solve this, but there are quite a few other approaches that work also.

Would be interested in what @nathanoehlman and @pedalpete have to say on this as I know they've done more at the application layer than I have :)

**Comment by madwill** [comment]
Thank you for such a quick response. 

I'll have a look at the identifying participant part of the rtc-signaller. I've already made something similar by registering the quickConnect id as a member of the user object being distributed in parallel by socket.io. 

I felt it was a bit sub-optimal as i needed manual matching of connection and user but its entirely doable and probably abstract-able to leave code as clean as possible. 

We currently run the beta with PeerJs and use their [media connection metadata](http://peerjs.com/docs/#mediaconnection-metadata) to differentiate screen stream from camera streams. 

Our main concern is PeerJs is not really supported anymore while your RTC suite is alive, lovely and really complete. 

I'm already looking forward to rtc-health as we run our teaching operation in Thailand regions outside of Bangkok where internet is sub par and good analysis could help us identify problematic nodes and do our best to fix hardware. 

Thanks again  for your time i'll follow gitter and google group!
