### ISSUE TITLE
Existing users will re-announce when any user in that room disconnected

### ISSUE THREAD

**Issue by betimer** [rtc-io/rtc-quickconnect#77]
The call gets setup already: A, B and C.

If A disconnected, it turns out B and C will re-announce.
Is this by design?

**Comment by nathanoehlman** [comment]
Hi @betimer,

Yes - that's by design. It helps to ensure that peers are connected to each other. For instance, if A's peer connections to B & C dropped for some reason, but A remained connected to the signaller, then the re-announce will cause B & C to automatically attempt to reconnect to A, and recover (restart) the peer connections.

If A is no longer connected to the signaller, then B & C will detect that they are connected to all the available participants, and will not attempt any reconnections.

Cheers,
Nathan

**Comment by betimer** [comment]
Cool. Thank you, Nathan.
